### ISSUE TITLE
UI for rebuy

### ISSUE THREAD

**Issue by HelgeWieding** [acebusters/poker-helper#114]
This  should be the same as the join modal. Where a user can select an amount to join the table.  It should automatically show up when the user hits 0 balance. 
To check wether the current table balance is 0 you can use the makeMyStackSelector.

**Comment by johannbarbie** [comment]
also have a look at the screen flow here: https://docs.google.com/drawings/d/1smdjRgbSFYSUogPOzoqWvgAzj_O2AMJQPTlCL2tMelw
